spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:sakila}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:yourLocalPassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.elasticsearch.uris=${ELASTICSEARCH_URI:http://localhost:9200}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

management.endpoints.web.exposure.include=health